//
// File generated by rootcint at Fri Sep 20 12:48:32 2002.
// Do NOT change. Changes will be lost next time file is generated
//
#include "GreenMonsterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

//______________________________________________________________________________
TBuffer &operator>>(TBuffer &buf, GreenMonster *&obj)
{
   // Read a pointer to an object of class GreenMonster.

   obj = (GreenMonster *) buf.ReadObject(GreenMonster::Class());
   return buf;
}

//______________________________________________________________________________
void GreenMonster::Streamer(TBuffer &R__b)
{
   // Stream an object of class GreenMonster.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void GreenMonster::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
   // Inspect the data members of an object of class GreenMonster.

   TClass *R__cl  = GreenMonster::IsA();
   Int_t   R__ncp = strlen(R__parent);
   if (R__ncp || R__cl || R__insp.IsA()) { }
   R__insp.Inspect(R__cl, R__parent, "fQObject", &fQObject);
   fQObject.ShowMembers(R__insp, strcat(R__parent,"fQObject.")); R__parent[R__ncp] = 0;
   R__insp.Inspect(R__cl, R__parent, "mainWidth", &mainWidth);
   R__insp.Inspect(R__cl, R__parent, "mainHeight", &mainHeight);
   R__insp.Inspect(R__cl, R__parent, "fUseCrate[4]", fUseCrate);
   R__insp.Inspect(R__cl, R__parent, "*fCrateNames[4]", &fCrateNames);
   R__insp.Inspect(R__cl, R__parent, "fCrateNumbers[4]", fCrateNumbers);
   R__insp.Inspect(R__cl, R__parent, "*fTimeBoard[4]", &fTimeBoard);
   R__insp.Inspect(R__cl, R__parent, "fBMW_TABID", &fBMW_TABID);
   R__insp.Inspect(R__cl, R__parent, "*changeStatusBtBMW", &changeStatusBtBMW);
   R__insp.Inspect(R__cl, R__parent, "*checkStatusBtBMW", &checkStatusBtBMW);
   R__insp.Inspect(R__cl, R__parent, "*switchLabelBMW", &switchLabelBMW);
   R__insp.Inspect(R__cl, R__parent, "*activeLabelBMW", &activeLabelBMW);
   R__insp.Inspect(R__cl, R__parent, "*statusLabelBMW", &statusLabelBMW);
   R__insp.Inspect(R__cl, R__parent, "*_ctimer", &_ctimer);
   TGMainFrame::ShowMembers(R__insp, R__parent);
}

//______________________________________________________________________________
const char *GreenMonster::Class_Name()
{
   // Return the class name for GreenMonster.
   return "GreenMonster";
}

// Static variable to hold initialization object
static GreenMonster::R__Init __gR__InitGreenMonster(0);

/********************************************************
* GreenMonsterDict.C
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableGreenMonsterDict();

extern "C" void G__set_cpp_environmentGreenMonsterDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("GreenMonster.h");
  G__cpp_reset_tagtableGreenMonsterDict();
}
class G__GreenMonsterDictdOC_tag {};

void* operator new(size_t size,G__GreenMonsterDictdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__GreenMonsterDictdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_GreenMonsterDictdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevGreenMonsterDict() { return(30051503); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GreenMonster */
static int G__GreenMonster_Connect_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,98,(long)((GreenMonster*)(G__getstructoffset()))->Connect((const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1])
,(void*)G__int(libp->para[2]),(const char*)G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Disconnect_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
      G__letint(result7,98,(long)((GreenMonster*)(G__getstructoffset()))->Disconnect((const char*)G__int(libp->para[0]),(void*)G__int(libp->para[1])
,(const char*)G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7,98,(long)((GreenMonster*)(G__getstructoffset()))->Disconnect((const char*)G__int(libp->para[0]),(void*)G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7,98,(long)((GreenMonster*)(G__getstructoffset()))->Disconnect((const char*)G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7,98,(long)((GreenMonster*)(G__getstructoffset()))->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_HighPriority_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->HighPriority((const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->HighPriority((const char*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_LowPriority_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->LowPriority((const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->LowPriority((const char*)G__int(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Double_t)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Long_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(const char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Long_t*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Char_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(UChar_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Short_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(UShort_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(ULong_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Emit_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Emit((const char*)G__int(libp->para[0]),(Float_t)G__double(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Destroyed_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Destroyed();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_ChangedBy_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->ChangedBy((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Message_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Message((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Class_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((GreenMonster*)(G__getstructoffset()))->Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Class_Name_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((GreenMonster*)(G__getstructoffset()))->Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Class_Version_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)((GreenMonster*)(G__getstructoffset()))->Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Dictionary_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_IsA_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const GreenMonster*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_ShowMembers_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Streamer_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_StreamerNVirtual_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_DeclFileName_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((GreenMonster*)(G__getstructoffset()))->DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_DeclFileLine_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((GreenMonster*)(G__getstructoffset()))->DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_ImplFileName_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((GreenMonster*)(G__getstructoffset()))->ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_ImplFileLine_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((GreenMonster*)(G__getstructoffset()))->ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_GreenMonster_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   GreenMonster *p=NULL;
      p = new GreenMonster(
(const TGWindow*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_ProcessMessage_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,98,(long)((GreenMonster*)(G__getstructoffset()))->ProcessMessage((Long_t)G__int(libp->para[0]),(Long_t)G__int(libp->para[1])
,(Long_t)G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_BMWDelayCheck_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->BMWDelayCheck();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GreenMonster_Init_6_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((GreenMonster*)(G__getstructoffset()))->Init();
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GreenMonster_GreenMonster_2_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   GreenMonster *p;
   p=new GreenMonster(*(GreenMonster*)G__int(libp->para[0]));
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GreenMonster G__TGreenMonster;
static int G__GreenMonster_wAGreenMonster_3_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (GreenMonster *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (GreenMonster *)((G__getstructoffset())+sizeof(GreenMonster)*i);
   else  delete (GreenMonster *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GreenMonster */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGreenMonsterDict {
 public:
  G__Sizep2memfuncGreenMonsterDict() {p=&G__Sizep2memfuncGreenMonsterDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGreenMonsterDict::*p)();
};

size_t G__get_sizep2memfuncGreenMonsterDict()
{
  G__Sizep2memfuncGreenMonsterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGreenMonsterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster))) {
     GreenMonster *G__Lderived;
     G__Lderived=(GreenMonster*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),G__get_linked_tagnum(&G__GreenMonsterDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGreenMonsterDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,
-1);
   G__setnewtype(-1,"Signed Character 1 byte",0);
   G__search_typename2("UChar_t",98,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Character 1 byte",0);
   G__search_typename2("Short_t",115,-1,0,
-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes",0);
   G__search_typename2("UShort_t",114,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes",0);
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes",0);
   G__search_typename2("UInt_t",104,-1,0,
-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes",0);
   G__search_typename2("Seek_t",105,-1,0,
-1);
   G__setnewtype(-1,"File pointer",0);
   G__search_typename2("Long_t",108,-1,0,
-1);
   G__setnewtype(-1,"Signed long integer 4 bytes",0);
   G__search_typename2("ULong_t",107,-1,0,
-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes",0);
   G__search_typename2("Float_t",102,-1,0,
-1);
   G__setnewtype(-1,"Float 4 bytes",0);
   G__search_typename2("Double_t",100,-1,0,
-1);
   G__setnewtype(-1,"Float 8 bytes",0);
   G__search_typename2("Text_t",99,-1,0,
-1);
   G__setnewtype(-1,"General string",0);
   G__search_typename2("Bool_t",98,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true)",0);
   G__search_typename2("Byte_t",98,-1,0,
-1);
   G__setnewtype(-1,"Byte (8 bits)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier",0);
   G__search_typename2("Option_t",99,-1,0,
-1);
   G__setnewtype(-1,"Option string",0);
   G__search_typename2("Ssiz_t",105,-1,0,
-1);
   G__setnewtype(-1,"String size",0);
   G__search_typename2("Real_t",102,-1,0,
-1);
   G__setnewtype(-1,"TVector and TMatrix element type",0);
   G__search_typename2("Streamer_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("VoidFuncPtr_t",89,-1,0,
-1);
   G__setnewtype(-1,"pointer to void function",0);
   G__search_typename2("FreeHookFun_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ReAllocFun_t",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ReAllocCFun_t",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Axis_t",100,-1,0,
-1);
   G__setnewtype(-1,"Axis values type",0);
   G__search_typename2("Stat_t",100,-1,0,
-1);
   G__setnewtype(-1,"Statistics type",0);
   G__search_typename2("Handle_t",107,-1,0,
-1);
   G__setnewtype(-1,"Generic resource handle",0);
   G__search_typename2("Display_t",107,-1,0,
-1);
   G__setnewtype(-1,"Display handle",0);
   G__search_typename2("Window_t",107,-1,0,
-1);
   G__setnewtype(-1,"Window handle",0);
   G__search_typename2("Pixmap_t",107,-1,0,
-1);
   G__setnewtype(-1,"Pixmap handle",0);
   G__search_typename2("Drawable_t",107,-1,0,
-1);
   G__setnewtype(-1,"Drawable handle",0);
   G__search_typename2("Region_t",107,-1,0,
-1);
   G__setnewtype(-1,"Region handle",0);
   G__search_typename2("Colormap_t",107,-1,0,
-1);
   G__setnewtype(-1,"Colormap handle",0);
   G__search_typename2("Cursor_t",107,-1,0,
-1);
   G__setnewtype(-1,"Cursor handle",0);
   G__search_typename2("FontH_t",107,-1,0,
-1);
   G__setnewtype(-1,"Font handle (as opposed to Font_t which is an index)",0);
   G__search_typename2("KeySym_t",107,-1,0,
-1);
   G__setnewtype(-1,"Key symbol handle",0);
   G__search_typename2("Atom_t",107,-1,0,
-1);
   G__setnewtype(-1,"WM token",0);
   G__search_typename2("GContext_t",107,-1,0,
-1);
   G__setnewtype(-1,"Graphics context handle (or pointer, needs to be long)",0);
   G__search_typename2("FontStruct_t",107,-1,0,
-1);
   G__setnewtype(-1,"Pointer to font structure",0);
   G__search_typename2("Mask_t",104,-1,0,
-1);
   G__setnewtype(-1,"Structure mask type",0);
   G__search_typename2("Time_t",107,-1,0,
-1);
   G__setnewtype(-1,"Event time",0);
   G__search_typename2("Font_t",115,-1,0,
-1);
   G__setnewtype(-1,"Font number",0);
   G__search_typename2("Style_t",115,-1,0,
-1);
   G__setnewtype(-1,"Style number",0);
   G__search_typename2("Marker_t",115,-1,0,
-1);
   G__setnewtype(-1,"Marker number",0);
   G__search_typename2("Width_t",115,-1,0,
-1);
   G__setnewtype(-1,"Line width",0);
   G__search_typename2("Color_t",115,-1,0,
-1);
   G__setnewtype(-1,"Color number",0);
   G__search_typename2("SCoord_t",115,-1,0,
-1);
   G__setnewtype(-1,"Screen coordinates",0);
   G__search_typename2("Coord_t",100,-1,0,
-1);
   G__setnewtype(-1,"Pad world coordinates",0);
   G__search_typename2("Angle_t",102,-1,0,
-1);
   G__setnewtype(-1,"Graphics angle",0);
   G__search_typename2("Size_t",102,-1,0,
-1);
   G__setnewtype(-1,"Attribute size",0);
   G__search_typename2("Int_t (*)(const char*xact, Int_t nb, void**ar, Int_t*iret)",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Func_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GreenMonster */
static void G__setup_memvarGreenMonster(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster));
   { GreenMonster *p; p=(GreenMonster*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mainWidth=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mainHeight=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,107,0,1,-1,G__defined_typename("ULong_t"),-2,4,"grnback=",0,"darkseagreen");
   G__memvar_setup((void*)NULL,98,0,0,-1,G__defined_typename("Bool_t"),-1,4,"fUseCrate[4]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TString),-1,-1,4,"fCrateNames[4]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fCrateNumbers[4]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenTB),-1,-1,4,"fTimeBoard[4]=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fBMW_TABID=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"changeStatusBtBMW=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGTextButton),-1,-1,4,"checkStatusBtBMW=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGLabel),-1,-1,4,"switchLabelBMW=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGLabel),-1,-1,4,"activeLabelBMW=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TGLabel),-1,-1,4,"statusLabelBMW=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__GreenMonsterDictLN_TTimer),-1,-1,4,"_ctimer=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGreenMonsterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGreenMonster(void) {
   /* GreenMonster */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster));
   G__memfunc_setup("Connect",714,G__GreenMonster_Connect_0_0,98,-1,G__defined_typename("Bool_t"),0,4,1,1,0,
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Disconnect",1034,G__GreenMonster_Disconnect_1_0,98,-1,G__defined_typename("Bool_t"),0,3,1,1,0,
"C - - 10 0 sig Y - - 0 0 rcvr "
"C - - 10 0 slt",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HighPriority",1250,G__GreenMonster_HighPriority_2_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal_name C - - 10 0 slot_name",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("LowPriority",1172,G__GreenMonster_LowPriority_3_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal_name C - - 10 0 slot_name",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_4_0,121,-1,-1,0,1,1,1,0,"C - - 10 - signal",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_5_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal d - 'Double_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_6_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal l - 'Long_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_7_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal C - - 10 - params",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_8_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal L - 'Long_t' 0 - paramArr",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_9_0,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal c - 'Char_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_0_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal b - 'UChar_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_1_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal s - 'Short_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_2_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal r - 'UShort_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_3_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal i - 'Int_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_4_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal h - 'UInt_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_5_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal k - 'ULong_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Emit",399,G__GreenMonster_Emit_6_1,121,-1,-1,0,2,1,1,0,
"C - - 10 - signal f - 'Float_t' 0 - param",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Destroyed",947,G__GreenMonster_Destroyed_7_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ChangedBy",869,G__GreenMonster_ChangedBy_8_1,121,-1,-1,0,1,1,1,0,"C - - 10 - method",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Message",709,G__GreenMonster_Message_9_1,121,-1,-1,0,1,1,1,0,"C - - 10 - msg",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Class",502,G__GreenMonster_Class_0_2,85,G__get_linked_tagnum(&G__GreenMonsterDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__GreenMonster_Class_Name_1_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__GreenMonster_Class_Version_2_2,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__GreenMonster_Dictionary_3_2,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__GreenMonster_IsA_4_2,85,G__get_linked_tagnum(&G__GreenMonsterDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__GreenMonster_ShowMembers_5_2,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__GreenMonster_Streamer_6_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GreenMonster_StreamerNVirtual_7_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__GreenMonster_DeclFileName_8_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__GreenMonster_DeclFileLine_9_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__GreenMonster_ImplFileName_0_3,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__GreenMonster_ImplFileLine_1_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GreenMonster",1241,G__GreenMonster_GreenMonster_2_3,105,G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),-1,0,3,1,1,0,
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ProcessMessage",1444,G__GreenMonster_ProcessMessage_4_3,98,-1,G__defined_typename("Bool_t"),0,3,1,1,0,
"l - 'Long_t' 0 - msg l - 'Long_t' 0 - parm1 "
"l - 'Long_t' 0 - parm2",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("BMWDelayCheck",1203,G__GreenMonster_BMWDelayCheck_5_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Init",404,G__GreenMonster_Init_6_3,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("BMWCheckStatus",1352,(G__InterfaceMethod)NULL,98,-1,G__defined_typename("Bool_t"),0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("BMWChangeStatus",1456,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("BMWActiveProbe",1338,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("BMWCheckActiveFlag",1690,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("InitGui",697,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("GreenMonster",1241,G__GreenMonster_GreenMonster_2_4,(int)('i'),G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),-1,0,1,1,1,0,"u 'GreenMonster' - 1 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~GreenMonster",1367,G__GreenMonster_wAGreenMonster_3_4,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGreenMonsterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
extern "C" void G__cpp_setup_globalGreenMonsterDict() {

   /* Setting up global variables */
   G__resetplocal();


   G__resetglobalenv();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
extern "C" void G__cpp_setup_funcGreenMonsterDict() {
   G__lastifuncposition();


   G__resetifuncposition();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GreenMonsterDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_GreenTB = { "GreenTB" , 99 , -1 };
G__linked_taginfo G__GreenMonsterDictLN_GreenMonster = { "GreenMonster" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGreenMonsterDict() {
  G__GreenMonsterDictLN_TClass.tagnum = -1 ;
  G__GreenMonsterDictLN_TTimer.tagnum = -1 ;
  G__GreenMonsterDictLN_TObject.tagnum = -1 ;
  G__GreenMonsterDictLN_TString.tagnum = -1 ;
  G__GreenMonsterDictLN_TGWindow.tagnum = -1 ;
  G__GreenMonsterDictLN_TGObject.tagnum = -1 ;
  G__GreenMonsterDictLN_TQObject.tagnum = -1 ;
  G__GreenMonsterDictLN_TQObjSender.tagnum = -1 ;
  G__GreenMonsterDictLN_TGFrame.tagnum = -1 ;
  G__GreenMonsterDictLN_TGCompositeFrame.tagnum = -1 ;
  G__GreenMonsterDictLN_TGMainFrame.tagnum = -1 ;
  G__GreenMonsterDictLN_TGLabel.tagnum = -1 ;
  G__GreenMonsterDictLN_TGTextButton.tagnum = -1 ;
  G__GreenMonsterDictLN_GreenTB.tagnum = -1 ;
  G__GreenMonsterDictLN_GreenMonster.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGreenMonsterDict() {

   /* Setting up class,struct,union tag entry */
   G__tagtable_setup(G__get_linked_tagnum(&G__GreenMonsterDictLN_GreenMonster),sizeof(GreenMonster),-1,29696,(char*)NULL,G__setup_memvarGreenMonster,G__setup_memfuncGreenMonster);
}
extern "C" void G__cpp_setupGreenMonsterDict(void) {
  G__check_setup_version(30051503,"G__cpp_setupGreenMonsterDict()");
  G__set_cpp_environmentGreenMonsterDict();
  G__cpp_setup_tagtableGreenMonsterDict();

  G__cpp_setup_inheritanceGreenMonsterDict();

  G__cpp_setup_typetableGreenMonsterDict();

  G__cpp_setup_memvarGreenMonsterDict();

  G__cpp_setup_memfuncGreenMonsterDict();
  G__cpp_setup_globalGreenMonsterDict();
  G__cpp_setup_funcGreenMonsterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGreenMonsterDict();
  return;
}
class G__cpp_setup_initGreenMonsterDict {
  public:
    G__cpp_setup_initGreenMonsterDict() { G__add_setup_func("GreenMonsterDict",(G__incsetup)(&G__cpp_setupGreenMonsterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGreenMonsterDict() { G__remove_setup_func("GreenMonsterDict"); }
};
G__cpp_setup_initGreenMonsterDict G__cpp_setup_initializerGreenMonsterDict;

